from dotenv import load_dotenv
from openai import OpenAI
import json
import os
import requests

load_dotenv()

client = OpenAI(
    api_key=os.environ.get("GROQ_API_KEY"),
    base_url="https://api.groq.com/openai/v1",
)


def run_command(command):
    result=os.system(command=command)
    return result


def get_weather(city: str):
    print(f"< Tool Called: get_weather > {city}")

    url = f"https://wttr.in/{city}?format=%C+%t"

    try:
        response = requests.get(url)

        if response.status_code == 200:
            return f"The weather in {city} is {response.text}"

        return "Weather API failed"

    except Exception as e:
        return f"Error: {str(e)}"


def add(x, y):
    print(f"< Tool Called: add > {x}, {y}")
    return x + y


available_tools = {
    "get_weather": {
        "fn": get_weather,
        "description": "Takes a city name as input and returns current weather"
    },

    "add": {
        "fn": add,
        "description": "Takes two numbers x and y and returns x + y"
    },

    "run_command":{
        "fn": run_command,
        "description":"Takes a command as input to execute on system and return the output"
    }
}

system_prompt = """
You are a helpful AI Assistant specialized in solving user queries.

You work in the following modes:
1. plan
2. action
3. observe
4. output

Rules:
- Always return ONLY ONE valid JSON object
- Never return markdown
- Never return text outside JSON
- Perform one step at a time
- Output must always be valid JSON

Output JSON format:

{
    "step": "plan | action | observe | output",
    "content": "string",
    "function": "string",
    "input": "string or object"
}

Available Tools:
- get-weather: Takes a city name as an input and returns the current weather for the city.
- run_command: Takes a command as input to execute on system and return the output.
"""

messages = [
    {
        "role": "system",
        "content": system_prompt
    }
]

while True:

    user_query = input("\n👨 You: ")

    if user_query.lower() in ["exit", "quit"]:
        print("👋 Exiting...")
        break

    messages.append({
        "role": "user",
        "content": user_query
    })

    while True:

        response = client.chat.completions.create(
            model="openai/gpt-oss-120b",
            response_format={"type": "json_object"},
            messages=messages
        )

        raw_output = response.choices[0].message.content

        try:
            parsed_output = json.loads(raw_output)

        except json.JSONDecodeError:
            print("\n❌ Invalid JSON generated by model")
            print(raw_output)
            break

        messages.append({
            "role": "assistant",
            "content": json.dumps(parsed_output)
        })

        step = parsed_output.get("step")

        if step == "plan":

            print(f"\n🧠: {parsed_output.get('content')}")
            continue

        elif step == "action":

            tool_name = parsed_output.get("function")
            tool_input = parsed_output.get("input")

            if tool_name not in available_tools:

                print(f"\n❌ Tool '{tool_name}' not found")
                break

            try:

                if tool_name == "add":

                    output = available_tools[tool_name]["fn"](
                        tool_input["x"],
                        tool_input["y"]
                    )

                else:

                    output = available_tools[tool_name]["fn"](
                        tool_input
                    )

                observation = {
                    "step": "observe",
                    "content": str(output)
                }

                print(f"\n👀 Observation: {output}")

                messages.append({
                    "role": "assistant",
                    "content": json.dumps(observation)
                })

                continue

            except Exception as e:

                print(f"\n❌ Tool execution failed: {str(e)}")
                break

        elif step == "output":

            print(f"\n🤖: {parsed_output.get('content')}")
            break

        else:

            print("\n❌ Unknown step received")
            print(parsed_output)
            break