from dotenv import load_dotenv
from openai import OpenAI
import json
import os
import requests


load_dotenv()


client = OpenAI(
    api_key=os.environ.get("GROQ_API_KEY"),
    base_url="https://api.groq.com/openai/v1",
)



def get_weather(city: str):
    print(f"< Tool Called: get_weather > {city}")

    url = f"https://wttr.in/{city}?format=%C+%t"

    try:
        response = requests.get(url)

        if response.status_code == 200:
            return f"The weather in {city} is {response.text}"

        return "Weather API failed"

    except Exception as e:
        return f"Error: {str(e)}"


def add(x, y):
    print(f"< Tool Called: add > {x}, {y}")
    return x + y




available_tools = {
    "get_weather": {
        "fn": get_weather,
        "description": "Takes a city name as input and returns current weather"
    },

    "add": {
        "fn": add,
        "description": "Takes two numbers x and y and returns x + y"
    }
}



system_prompt = """
You are a helpful AI Assistant specialized in solving user queries.

You work in the following modes:
1. plan
2. action
3. observe
4. output

Your job:
- Understand the user query
- Plan step-by-step
- Select the correct tool
- Execute ONE tool at a time
- Wait for observation
- Finally answer the user

STRICT RULES:
- Always return ONLY ONE valid JSON object
- Never return multiple JSON objects
- Never return markdown
- Never return text outside JSON
- Output must always be valid parsable JSON
- Perform only ONE step at a time
- Carefully analyze the user query

Output JSON format:

{
    "step": "plan | action | observe | output",
    "content": "string",
    "function": "string",
    "input": "string or object"
}

Available Tools:

1. get_weather
   Description:
   Takes a city name and returns current weather.

   Example:
   {
      "step":"action",
      "function":"get_weather",
      "input":"Delhi"
   }

2. add
   Description:
   Takes two numbers and returns their sum.

   Example:
   {
      "step":"action",
      "function":"add",
      "input":{
          "x":10,
          "y":20
      }
   }

Example Flow:

User:
What is the weather in Delhi?

Assistant:
{
   "step":"plan",
   "content":"The user wants weather information for Delhi"
}

Assistant:
{
   "step":"plan",
   "content":"I should use the get_weather tool"
}

Assistant:
{
   "step":"action",
   "function":"get_weather",
   "input":"Delhi"
}

Assistant:
{
   "step":"output",
   "content":"The weather in Delhi is Sunny 32C"
}
"""



messages = [
    {
        "role": "system",
        "content": system_prompt
    }
]



user_query = input("> ")

messages.append({
    "role": "user",
    "content": user_query
})



while True:

    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        response_format={"type": "json_object"},
        messages=messages
    )

    raw_output = response.choices[0].message.content


    print("\nRAW MODEL OUTPUT:")
    print(raw_output)


    try:
        parsed_output = json.loads(raw_output)

    except json.JSONDecodeError:
        print("\n❌ Invalid JSON generated by model")
        break

    messages.append({
        "role": "assistant",
        "content": json.dumps(parsed_output)
    })

    step = parsed_output.get("step")



    if step == "plan":

        print(f"\n🧠: {parsed_output.get('content')}")
        continue


    elif step == "action":

        tool_name = parsed_output.get("function")
        tool_input = parsed_output.get("input")

        if tool_name not in available_tools:

            print(f"\n❌ Tool '{tool_name}' not found")
            break

        try:

        
            if tool_name == "add":

                output = available_tools[tool_name]["fn"](
                    tool_input["x"],
                    tool_input["y"]
                )

            else:

                output = available_tools[tool_name]["fn"](
                    tool_input
                )


            observation = {
                "step": "observe",
                "content": str(output)
            }

            print(f"\n👀 Observation: {output}")

            messages.append({
                "role": "assistant",
                "content": json.dumps(observation)
            })

            continue

        except Exception as e:

            print(f"\n❌ Tool execution failed: {str(e)}")
            break



    elif step == "output":

        print(f"\n🤖: {parsed_output.get('content')}")
        break


    else:

        print("\n❌ Unknown step received")
        print(parsed_output)
        break